version: 2
updates:
    - package-ecosystem: "github-actions"
      target-branch: "main"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "wednesday"
          time: "11:00"
          timezone: "Europe/Berlin"
      commit-message:
          prefix: "Dependency"
          include: "scope"
      labels:
          - "dependencies"
    - package-ecosystem: "npm"
      target-branch: "main"
      directory: "/frontend/webEditor"
      schedule:
          interval: "weekly"
          day: "wednesday"
          time: "11:00"
          timezone: "Europe/Berlin"
      commit-message:
          prefix: "Dependency"
          include: "scope"
      labels:
          - "dependencies"
    - package-ecosystem: "maven"
      target-branch: "main"
      directory: "/backend/analysisBackendServer"
      schedule:
          interval: "weekly"
          day: "wednesday"
          time: "11:00"
          timezone: "Europe/Berlin"
      commit-message:
          prefix: "Dependency"
          include: "scope"
      labels:
          - "dependencies"
          - "minor"
